use clap::{Parser, Subcommand};
use std::path::PathBuf;

mod auth;
mod cache;
mod client;
mod config;
mod fetch;
mod generation;
mod manifest;
mod platform;
mod template;
mod write;

#[derive(Parser)]
#[command(
    name = "akeyless-install-secrets",
    version,
    about = "Fetch Akeyless secrets at Nix activation time"
)]
struct Cli {
    #[command(subcommand)]
    command: Commands,
}

#[derive(Subcommand)]
enum Commands {
    /// Fetch secrets and install them to their target paths
    Install {
        /// Path to the manifest file (generated by Nix module)
        manifest: PathBuf,

        /// Ignore owner/group lookups (for dry activation)
        #[arg(long)]
        ignore_passwd: bool,
    },

    /// Validate manifest and test authentication (dry run)
    Check {
        /// Path to the manifest file
        manifest: PathBuf,
    },

    /// Verify all secret paths exist in Akeyless
    Validate {
        /// Path to the manifest file
        manifest: PathBuf,
    },
}

#[tokio::main]
async fn main() -> anyhow::Result<()> {
    let cli = Cli::parse();

    match cli.command {
        Commands::Install {
            manifest,
            ignore_passwd,
        } => {
            let cfg = config::load()?;
            let manifest = manifest::load(&manifest)?;
            let token = auth::authenticate(&cfg).await?;
            let client = client::AkeylessClient::new(&cfg.api_url, &token);

            let secrets = fetch::fetch_all(&client, &manifest.secrets).await?;
            let rendered = template::render_all(&manifest.templates, &secrets)?;

            let generation_info = generation::create(&manifest, &secrets, &rendered, ignore_passwd)?;
            generation::switch(&manifest, &generation_info)?;
            generation::prune(&manifest)?;

            if cfg.cache.enabled {
                cache::store(&cfg, &secrets)?;
            }

            eprintln!(
                "akeyless-nix: installed {} secrets, {} templates (generation {})",
                secrets.len(),
                rendered.len(),
                generation_info.number
            );
        }

        Commands::Check { manifest } => {
            let cfg = config::load()?;
            let manifest = manifest::load(&manifest)?;
            let token = auth::authenticate(&cfg).await?;
            let client = client::AkeylessClient::new(&cfg.api_url, &token);

            eprintln!("akeyless-nix: auth OK (token acquired)");
            eprintln!("akeyless-nix: manifest has {} secrets, {} templates",
                manifest.secrets.len(), manifest.templates.len());

            // Dry-run fetch to verify all paths exist
            for secret in &manifest.secrets {
                match client.get_secret(&secret.akeyless_path).await {
                    Ok(_) => eprintln!("  [ok] {}", secret.akeyless_path),
                    Err(e) => eprintln!("  [!!] {} — {e}", secret.akeyless_path),
                }
            }
        }

        Commands::Validate { manifest } => {
            let manifest = manifest::load(&manifest)?;
            eprintln!("akeyless-nix: manifest valid ({} secrets, {} templates)",
                manifest.secrets.len(), manifest.templates.len());
        }
    }

    Ok(())
}
