use clap::{Parser, Subcommand, ValueEnum};
use std::path::PathBuf;

mod auth;
mod cache;
mod client;
mod config;
mod fetch;
mod generation;
mod installer;
mod manifest;
mod platform;
mod template;
mod traits;
mod write;

#[derive(Parser)]
#[command(
    name = "akeyless-install-secrets",
    version,
    about = "Fetch Akeyless secrets at Nix activation time"
)]
struct Cli {
    #[command(subcommand)]
    command: Commands,
}

/// Which template engine to use for rendering.
#[derive(Clone, Copy, Debug, Default, ValueEnum)]
enum TemplateEngineKind {
    /// Hash-based placeholder substitution (legacy, default)
    #[default]
    Placeholder,
    /// MiniJinja-backed rendering via igata (`[= var =]` syntax)
    Igata,
}

#[derive(Subcommand)]
enum Commands {
    /// Fetch secrets and install them to their target paths
    Install {
        /// Path to the manifest file (generated by Nix module)
        manifest: PathBuf,

        /// Ignore owner/group lookups (for dry activation)
        #[arg(long)]
        ignore_passwd: bool,

        /// Template engine to use for rendering
        #[arg(long, value_enum, default_value_t = TemplateEngineKind::Placeholder)]
        template_engine: TemplateEngineKind,
    },

    /// Validate manifest and test authentication (dry run)
    Check {
        /// Path to the manifest file
        manifest: PathBuf,
    },

    /// Verify all secret paths exist in Akeyless
    Validate {
        /// Path to the manifest file
        manifest: PathBuf,
    },
}

#[tokio::main]
async fn main() -> anyhow::Result<()> {
    let cli = Cli::parse();

    match cli.command {
        Commands::Install {
            manifest,
            ignore_passwd,
            template_engine,
        } => {
            let cfg = config::load()?;
            let manifest = manifest::Manifest::load(&manifest)?;
            let token = auth::authenticate(&cfg).await?;
            let client = client::AkeylessClient::new(&cfg.api_url, &token);
            let fs_cache = cache::FsCache::new(&cfg);

            let cache_ref: Option<&dyn traits::CacheStore> = if cfg.cache.enabled {
                Some(&fs_cache)
            } else {
                None
            };

            let placeholder_engine = template::PlaceholderEngine;
            let igata_engine = template::IgataEngine::new();
            let engine: &dyn traits::TemplateEngine = match template_engine {
                TemplateEngineKind::Placeholder => &placeholder_engine,
                TemplateEngineKind::Igata => &igata_engine,
            };
            let inst = installer::Installer::new(&client, engine, cache_ref);
            let result = inst.install(&manifest, ignore_passwd).await?;

            eprintln!("akeyless-nix: installed {result}");
        }

        Commands::Check { manifest } => {
            let cfg = config::load()?;
            let manifest = manifest::Manifest::load(&manifest)?;
            let token = auth::authenticate(&cfg).await?;
            let client = client::AkeylessClient::new(&cfg.api_url, &token);

            eprintln!("akeyless-nix: auth OK (token acquired)");

            let engine = template::PlaceholderEngine;
            let inst = installer::Installer::new(&client, &engine, None);
            let results = inst.check(&manifest).await?;

            for (path, ok) in &results {
                if *ok {
                    eprintln!("  [ok] {path}");
                } else {
                    eprintln!("  [!!] {path}");
                }
            }

            let ok_count = results.iter().filter(|(_, ok)| *ok).count();
            eprintln!("akeyless-nix: {ok_count}/{} secrets accessible", results.len());
        }

        Commands::Validate { manifest } => {
            let manifest = manifest::Manifest::load(&manifest)?;
            eprintln!("akeyless-nix: manifest valid ({} secrets, {} templates)",
                manifest.secrets.len(), manifest.templates.len());
        }
    }

    Ok(())
}

#[cfg(test)]
mod cli_tests {
    use super::*;
    use clap::Parser;

    #[test]
    fn parse_install_subcommand() {
        let cli = Cli::try_parse_from([
            "akeyless-install-secrets",
            "install",
            "/path/to/manifest.json",
        ])
        .unwrap();
        match cli.command {
            Commands::Install {
                manifest,
                ignore_passwd,
                template_engine,
            } => {
                assert_eq!(manifest, PathBuf::from("/path/to/manifest.json"));
                assert!(!ignore_passwd);
                assert!(matches!(template_engine, TemplateEngineKind::Placeholder));
            }
            _ => panic!("expected Install command"),
        }
    }

    #[test]
    fn parse_install_with_ignore_passwd() {
        let cli = Cli::try_parse_from([
            "akeyless-install-secrets",
            "install",
            "--ignore-passwd",
            "/manifest.json",
        ])
        .unwrap();
        match cli.command {
            Commands::Install { ignore_passwd, .. } => assert!(ignore_passwd),
            _ => panic!("expected Install command"),
        }
    }

    #[test]
    fn parse_install_with_igata_engine() {
        let cli = Cli::try_parse_from([
            "akeyless-install-secrets",
            "install",
            "--template-engine",
            "igata",
            "/manifest.json",
        ])
        .unwrap();
        match cli.command {
            Commands::Install {
                template_engine, ..
            } => assert!(matches!(template_engine, TemplateEngineKind::Igata)),
            _ => panic!("expected Install command"),
        }
    }

    #[test]
    fn parse_check_subcommand() {
        let cli = Cli::try_parse_from([
            "akeyless-install-secrets",
            "check",
            "/manifest.json",
        ])
        .unwrap();
        match cli.command {
            Commands::Check { manifest } => {
                assert_eq!(manifest, PathBuf::from("/manifest.json"));
            }
            _ => panic!("expected Check command"),
        }
    }

    #[test]
    fn parse_validate_subcommand() {
        let cli = Cli::try_parse_from([
            "akeyless-install-secrets",
            "validate",
            "/manifest.json",
        ])
        .unwrap();
        match cli.command {
            Commands::Validate { manifest } => {
                assert_eq!(manifest, PathBuf::from("/manifest.json"));
            }
            _ => panic!("expected Validate command"),
        }
    }

    #[test]
    fn parse_no_subcommand_fails() {
        let result = Cli::try_parse_from(["akeyless-install-secrets"]);
        assert!(result.is_err(), "missing subcommand should fail");
    }

    #[test]
    fn parse_unknown_subcommand_fails() {
        let result = Cli::try_parse_from(["akeyless-install-secrets", "unknown"]);
        assert!(result.is_err(), "unknown subcommand should fail");
    }

    #[test]
    fn parse_install_missing_manifest_fails() {
        let result = Cli::try_parse_from(["akeyless-install-secrets", "install"]);
        assert!(result.is_err(), "install without manifest should fail");
    }

    #[test]
    fn parse_install_invalid_engine_fails() {
        let result = Cli::try_parse_from([
            "akeyless-install-secrets",
            "install",
            "--template-engine",
            "jinja2",
            "/manifest.json",
        ]);
        assert!(result.is_err(), "invalid template engine should fail");
    }

    #[test]
    fn template_engine_kind_default_is_placeholder() {
        assert!(matches!(
            TemplateEngineKind::default(),
            TemplateEngineKind::Placeholder
        ));
    }
}

/// End-to-end integration tests that exercise the full install flow
/// using mock providers and a temporary filesystem.
#[cfg(test)]
mod integration_tests {
    use std::collections::BTreeMap;

    use async_trait::async_trait;

    use crate::fetch;
    use crate::generation;
    use crate::manifest::{Manifest, SecretSpec, TemplateSpec};
    use crate::template;
    use crate::traits::{CacheStore, SecretProvider};
    use crate::write::FsFileWriter;

    struct MockProvider {
        secrets: BTreeMap<String, String>,
    }

    #[async_trait]
    impl SecretProvider for MockProvider {
        async fn get_secret(&self, path: &str) -> anyhow::Result<String> {
            self.secrets
                .get(path)
                .cloned()
                .ok_or_else(|| anyhow::anyhow!("not found: {path}"))
        }
    }

    struct InMemoryCache {
        data: std::sync::Mutex<Option<BTreeMap<String, String>>>,
    }

    impl InMemoryCache {
        fn new() -> Self {
            Self {
                data: std::sync::Mutex::new(None),
            }
        }
    }

    impl CacheStore for InMemoryCache {
        fn store(&self, secrets: &BTreeMap<String, String>) -> anyhow::Result<()> {
            *self.data.lock().unwrap() = Some(secrets.clone());
            Ok(())
        }
        fn load(&self) -> anyhow::Result<Option<BTreeMap<String, String>>> {
            Ok(self.data.lock().unwrap().clone())
        }
    }

    #[tokio::test]
    async fn test_full_install_flow() {
        let dir = std::env::temp_dir().join("akeyless-nix-test-e2e");
        let _ = std::fs::remove_dir_all(&dir);
        std::fs::create_dir_all(&dir).unwrap();

        // Set up mock secrets
        let mut mock_secrets = BTreeMap::new();
        mock_secrets.insert("/pleme/db-password".into(), "p@ssw0rd".into());
        mock_secrets.insert("/pleme/api-token".into(), "tok-123".into());

        let provider = MockProvider {
            secrets: mock_secrets,
        };

        // Build the template placeholder
        let hash = template::sha256_hex("/pleme/api-token");
        let placeholder = format!("<AKEYLESS:{hash}:PLACEHOLDER>");

        let secret_target = dir.join("secrets").join("db-password");
        let tmpl_target = dir.join("secrets").join("app-config.yaml");

        let manifest = Manifest {
            secrets: vec![
                SecretSpec::for_test("/pleme/db-password", &secret_target.to_string_lossy()),
                SecretSpec::for_test(
                    "/pleme/api-token",
                    &dir.join("secrets").join("api-token").to_string_lossy(),
                ),
            ],
            templates: vec![TemplateSpec::for_test(
                "app-config.yaml",
                &format!("database:\n  password: unused\napi:\n  token: {placeholder}\n"),
                &tmpl_target.to_string_lossy(),
            )],
            generations_dir: dir.join("generations").to_string_lossy().to_string(),
            symlink_path: dir.join("current").to_string_lossy().to_string(),
            keep_generations: 2,
        };

        // Step 1: Fetch via mock provider
        let secrets = fetch::fetch_all(&provider, &manifest.secrets).await.unwrap();
        assert_eq!(secrets.len(), 2);

        // Step 2: Render templates
        let engine = template::PlaceholderEngine;
        let rendered = template::render_all(&engine, &manifest.templates, &secrets).unwrap();
        assert_eq!(rendered.len(), 1);
        assert!(rendered[0].content.contains("tok-123"));

        // Step 3: Create generation via FsFileWriter
        let writer = FsFileWriter;
        let generation_info =
            generation::create_with_writer(&manifest, &secrets, &rendered, true, &writer).unwrap();
        assert_eq!(generation_info.number, 1);

        // Step 4: Switch symlinks
        generation::switch_with_writer(&manifest, &generation_info, &rendered, &writer).unwrap();

        // Step 5: Verify symlinks work
        assert!(secret_target.is_symlink());
        assert_eq!(
            std::fs::read_to_string(&secret_target).unwrap(),
            "p@ssw0rd"
        );
        assert!(tmpl_target.is_symlink());
        let rendered_config = std::fs::read_to_string(&tmpl_target).unwrap();
        assert!(rendered_config.contains("token: tok-123"));

        // Step 6: Cache via in-memory store
        let cache = InMemoryCache::new();
        cache.store(&secrets).unwrap();
        let cached = cache.load().unwrap().unwrap();
        assert_eq!(cached["/pleme/db-password"], "p@ssw0rd");

        // Step 7: Create a second generation and prune
        let g2 = generation::create_with_writer(&manifest, &secrets, &rendered, true, &writer)
            .unwrap();
        assert_eq!(g2.number, 2);
        let g3 = generation::create_with_writer(&manifest, &secrets, &rendered, true, &writer)
            .unwrap();
        assert_eq!(g3.number, 3);

        generation::prune(&manifest).unwrap();

        // Only 2 generations should remain (keep_generations = 2)
        let mut remaining: Vec<u64> = std::fs::read_dir(dir.join("generations"))
            .unwrap()
            .filter_map(|e| e.ok())
            .filter_map(|e| e.file_name().to_str()?.parse::<u64>().ok())
            .collect();
        remaining.sort();
        assert_eq!(remaining, vec![2, 3]);

        let _ = std::fs::remove_dir_all(&dir);
    }

    #[tokio::test]
    async fn test_install_flow_with_fetch_failure() {
        let provider = MockProvider {
            secrets: BTreeMap::new(),
        };
        let specs = vec![SecretSpec::for_test("/does/not/exist", "/tmp/irrelevant")];

        let result = fetch::fetch_all(&provider, &specs).await;
        assert!(result.is_err());
        let err_msg = result.unwrap_err().to_string();
        assert!(err_msg.contains("not found"), "error should mention 'not found': {err_msg}");
    }

    #[tokio::test]
    async fn test_full_install_flow_with_igata_engine() {
        let dir = std::env::temp_dir().join("akeyless-nix-test-e2e-igata");
        let _ = std::fs::remove_dir_all(&dir);
        std::fs::create_dir_all(&dir).unwrap();

        let mut mock_secrets = BTreeMap::new();
        mock_secrets.insert("/pleme/db-host".into(), "db.example.com".into());
        mock_secrets.insert("/pleme/db-pass".into(), "s3cret".into());

        let provider = MockProvider {
            secrets: mock_secrets,
        };

        let tmpl_target = dir.join("secrets").join("db-config");
        let manifest = Manifest {
            secrets: vec![
                SecretSpec::for_test(
                    "/pleme/db-host",
                    &dir.join("secrets").join("db-host").to_string_lossy(),
                ),
                SecretSpec::for_test(
                    "/pleme/db-pass",
                    &dir.join("secrets").join("db-pass").to_string_lossy(),
                ),
            ],
            templates: vec![TemplateSpec::for_test(
                "db-config",
                "host=[= pleme_db_host =]\npass=[= pleme_db_pass =]",
                &tmpl_target.to_string_lossy(),
            )],
            generations_dir: dir.join("generations").to_string_lossy().to_string(),
            symlink_path: dir.join("current").to_string_lossy().to_string(),
            keep_generations: 2,
        };

        let secrets = fetch::fetch_all(&provider, &manifest.secrets).await.unwrap();
        assert_eq!(secrets.len(), 2);

        let engine = template::IgataEngine::new();
        let rendered = template::render_all(&engine, &manifest.templates, &secrets).unwrap();
        assert_eq!(rendered.len(), 1);
        assert_eq!(rendered[0].content, "host=db.example.com\npass=s3cret");

        let writer = FsFileWriter;
        let generation_info =
            generation::create_with_writer(&manifest, &secrets, &rendered, true, &writer).unwrap();
        generation::switch_with_writer(&manifest, &generation_info, &rendered, &writer).unwrap();

        assert!(tmpl_target.is_symlink());
        let content = std::fs::read_to_string(&tmpl_target).unwrap();
        assert_eq!(content, "host=db.example.com\npass=s3cret");

        let _ = std::fs::remove_dir_all(&dir);
    }

    #[tokio::test]
    async fn test_install_flow_with_cache_roundtrip() {
        let dir = std::env::temp_dir().join("akeyless-nix-test-e2e-cache");
        let _ = std::fs::remove_dir_all(&dir);
        std::fs::create_dir_all(&dir).unwrap();

        let mut mock_secrets = BTreeMap::new();
        mock_secrets.insert("/app/token".into(), "tok-abc".into());

        let provider = MockProvider {
            secrets: mock_secrets,
        };

        let manifest = Manifest {
            secrets: vec![SecretSpec::for_test(
                "/app/token",
                &dir.join("token").to_string_lossy(),
            )],
            templates: vec![],
            generations_dir: dir.join("generations").to_string_lossy().to_string(),
            symlink_path: dir.join("current").to_string_lossy().to_string(),
            keep_generations: 2,
        };

        let secrets = fetch::fetch_all(&provider, &manifest.secrets).await.unwrap();

        let cache = InMemoryCache::new();
        cache.store(&secrets).unwrap();

        let loaded = cache.load().unwrap().unwrap();
        assert_eq!(loaded["/app/token"], "tok-abc");

        let empty_provider = MockProvider {
            secrets: BTreeMap::new(),
        };
        let result = fetch::fetch_all(&empty_provider, &manifest.secrets).await;
        assert!(result.is_err(), "empty provider should fail");

        let fallback = cache.load().unwrap().unwrap();
        assert_eq!(fallback["/app/token"], "tok-abc", "cache still has data");

        let _ = std::fs::remove_dir_all(&dir);
    }

    #[tokio::test]
    async fn test_empty_manifest_creates_valid_generation() {
        let dir = std::env::temp_dir().join("akeyless-nix-test-e2e-empty");
        let _ = std::fs::remove_dir_all(&dir);
        std::fs::create_dir_all(&dir).unwrap();

        let provider = MockProvider {
            secrets: BTreeMap::new(),
        };

        let manifest = Manifest {
            secrets: vec![],
            templates: vec![],
            generations_dir: dir.join("generations").to_string_lossy().to_string(),
            symlink_path: dir.join("current").to_string_lossy().to_string(),
            keep_generations: 2,
        };

        let secrets = fetch::fetch_all(&provider, &manifest.secrets).await.unwrap();
        assert!(secrets.is_empty());

        let engine = template::PlaceholderEngine;
        let rendered = template::render_all(&engine, &manifest.templates, &secrets).unwrap();
        assert!(rendered.is_empty());

        let writer = FsFileWriter;
        let generation_info =
            generation::create_with_writer(&manifest, &secrets, &rendered, true, &writer).unwrap();
        assert_eq!(generation_info.number, 1);

        generation::switch_with_writer(&manifest, &generation_info, &rendered, &writer).unwrap();
        let current = dir.join("current");
        assert!(current.is_symlink());
        assert_eq!(std::fs::read_link(&current).unwrap(), generation_info.path);

        let _ = std::fs::remove_dir_all(&dir);
    }
}
