use std::path::Path;

use anyhow::{Context, Result};
use serde::Deserialize;

#[derive(Debug, Deserialize)]
pub struct Manifest {
    pub secrets: Vec<SecretSpec>,
    #[serde(default)]
    pub templates: Vec<TemplateSpec>,
    pub generations_dir: String,
    pub symlink_path: String,
    #[serde(default = "default_keep")]
    pub keep_generations: u32,
}

fn default_keep() -> u32 {
    2
}

#[derive(Debug, Deserialize)]
pub struct SecretSpec {
    /// Path in Akeyless vault (e.g., "/pleme/prod/db-password")
    pub akeyless_path: String,
    /// Local file path to write the secret value
    pub file_path: String,
    /// File permission mode (octal string, e.g., "0600")
    #[serde(default = "default_mode")]
    pub mode: String,
    /// File owner (username or empty for current user)
    #[serde(default)]
    pub owner: String,
    /// File group (group name or empty for current group)
    #[serde(default)]
    pub group: String,
    /// File owner UID (alternative to owner name)
    #[serde(default)]
    pub uid: Option<u32>,
    /// File group GID (alternative to group name)
    #[serde(default)]
    pub gid: Option<u32>,
    /// Systemd units to restart when this secret changes (`NixOS` only).
    /// Parsed from the manifest for completeness but acted upon by
    /// the `NixOS` activation script, not by the Rust binary.
    #[serde(default)]
    #[allow(dead_code)]
    pub restart_units: Vec<String>,
    /// Systemd units to reload when this secret changes (`NixOS` only).
    /// Parsed from the manifest for completeness but acted upon by
    /// the `NixOS` activation script, not by the Rust binary.
    #[serde(default)]
    #[allow(dead_code)]
    pub reload_units: Vec<String>,
}

fn default_mode() -> String {
    "0400".to_string()
}

#[derive(Debug, Deserialize)]
pub struct TemplateSpec {
    /// Template name (for symlink naming)
    pub name: String,
    /// Template content with placeholders
    pub content: String,
    /// Local file path to write the rendered template
    pub file_path: String,
    /// File permission mode
    #[serde(default = "default_mode")]
    pub mode: String,
    /// File owner
    #[serde(default)]
    pub owner: String,
    /// File group
    #[serde(default)]
    pub group: String,
    /// File owner UID (alternative to owner name)
    #[serde(default)]
    pub uid: Option<u32>,
    /// File group GID (alternative to group name)
    #[serde(default)]
    pub gid: Option<u32>,
}

#[cfg(test)]
impl SecretSpec {
    /// Create a minimal `SecretSpec` for testing with only required fields.
    pub fn for_test(akeyless_path: &str, file_path: &str) -> Self {
        Self {
            akeyless_path: akeyless_path.into(),
            file_path: file_path.into(),
            mode: "0400".into(),
            owner: String::new(),
            group: String::new(),
            uid: None,
            gid: None,
            restart_units: vec![],
            reload_units: vec![],
        }
    }
}

#[cfg(test)]
impl TemplateSpec {
    /// Create a minimal `TemplateSpec` for testing with only required fields.
    pub fn for_test(name: &str, content: &str, file_path: &str) -> Self {
        Self {
            name: name.into(),
            content: content.into(),
            file_path: file_path.into(),
            mode: "0600".into(),
            owner: String::new(),
            group: String::new(),
            uid: None,
            gid: None,
        }
    }
}

/// Load and parse a manifest JSON file from disk.
///
/// The manifest is generated by the Nix module at build time and consumed
/// by `akeyless-install-secrets` at activation time.
pub fn load(path: &Path) -> Result<Manifest> {
    let content = std::fs::read_to_string(path)
        .with_context(|| format!("reading manifest {}", path.display()))?;
    serde_json::from_str(&content)
        .with_context(|| format!("parsing manifest {}", path.display()))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_parse_manifest() {
        let json = r#"{
            "secrets": [
                {
                    "akeyless_path": "/pleme/test/hello",
                    "file_path": "/tmp/hello",
                    "mode": "0600"
                }
            ],
            "templates": [],
            "generations_dir": "/tmp/gens",
            "symlink_path": "/tmp/current",
            "keep_generations": 2
        }"#;
        let manifest: Manifest = serde_json::from_str(json).unwrap();
        assert_eq!(manifest.secrets.len(), 1);
        assert_eq!(manifest.secrets[0].akeyless_path, "/pleme/test/hello");
        assert_eq!(manifest.secrets[0].mode, "0600");
        assert_eq!(manifest.keep_generations, 2);
    }

    #[test]
    fn test_default_mode() {
        let json = r#"{
            "secrets": [{"akeyless_path": "/test", "file_path": "/tmp/test"}],
            "templates": [],
            "generations_dir": "/tmp/g",
            "symlink_path": "/tmp/s"
        }"#;
        let manifest: Manifest = serde_json::from_str(json).unwrap();
        assert_eq!(manifest.secrets[0].mode, "0400");
        assert_eq!(manifest.keep_generations, 2);
    }

    #[test]
    fn test_uid_gid_parsing() {
        let json = r#"{
            "secrets": [
                {
                    "akeyless_path": "/test",
                    "file_path": "/tmp/test",
                    "uid": 1000,
                    "gid": 100
                }
            ],
            "templates": [
                {
                    "name": "tmpl",
                    "content": "hello",
                    "file_path": "/tmp/tmpl",
                    "uid": 0,
                    "gid": 0
                }
            ],
            "generations_dir": "/tmp/g",
            "symlink_path": "/tmp/s"
        }"#;
        let manifest: Manifest = serde_json::from_str(json).unwrap();
        assert_eq!(manifest.secrets[0].uid, Some(1000));
        assert_eq!(manifest.secrets[0].gid, Some(100));
        assert_eq!(manifest.templates[0].uid, Some(0));
        assert_eq!(manifest.templates[0].gid, Some(0));
    }

    #[test]
    fn test_uid_gid_defaults_to_none() {
        let json = r#"{
            "secrets": [{"akeyless_path": "/test", "file_path": "/tmp/test"}],
            "templates": [],
            "generations_dir": "/tmp/g",
            "symlink_path": "/tmp/s"
        }"#;
        let manifest: Manifest = serde_json::from_str(json).unwrap();
        assert_eq!(manifest.secrets[0].uid, None);
        assert_eq!(manifest.secrets[0].gid, None);
    }

    #[test]
    fn test_restart_reload_units_parsing() {
        let json = r#"{
            "secrets": [
                {
                    "akeyless_path": "/test",
                    "file_path": "/tmp/test",
                    "restart_units": ["nginx.service", "app.service"],
                    "reload_units": ["haproxy.service"]
                }
            ],
            "templates": [],
            "generations_dir": "/tmp/g",
            "symlink_path": "/tmp/s"
        }"#;
        let manifest: Manifest = serde_json::from_str(json).unwrap();
        assert_eq!(manifest.secrets[0].restart_units, vec!["nginx.service", "app.service"]);
        assert_eq!(manifest.secrets[0].reload_units, vec!["haproxy.service"]);
    }

    #[test]
    fn test_restart_reload_units_default_empty() {
        let json = r#"{
            "secrets": [{"akeyless_path": "/test", "file_path": "/tmp/test"}],
            "templates": [],
            "generations_dir": "/tmp/g",
            "symlink_path": "/tmp/s"
        }"#;
        let manifest: Manifest = serde_json::from_str(json).unwrap();
        assert!(manifest.secrets[0].restart_units.is_empty());
        assert!(manifest.secrets[0].reload_units.is_empty());
    }

    #[test]
    fn test_empty_manifest() {
        let json = r#"{
            "secrets": [],
            "templates": [],
            "generations_dir": "/tmp/g",
            "symlink_path": "/tmp/s"
        }"#;
        let manifest: Manifest = serde_json::from_str(json).unwrap();
        assert!(manifest.secrets.is_empty());
        assert!(manifest.templates.is_empty());
        assert_eq!(manifest.keep_generations, 2);
    }

    #[test]
    fn test_load_manifest_from_file() {
        let dir = std::env::temp_dir().join("akeyless-nix-test-manifest-file");
        let _ = std::fs::remove_dir_all(&dir);
        std::fs::create_dir_all(&dir).unwrap();

        let json = r#"{
            "secrets": [
                {
                    "akeyless_path": "/pleme/token",
                    "file_path": "/tmp/token",
                    "mode": "0600",
                    "uid": 1000,
                    "gid": 100
                }
            ],
            "templates": [
                {
                    "name": "config",
                    "content": "token: placeholder",
                    "file_path": "/tmp/config",
                    "uid": 0,
                    "gid": 0
                }
            ],
            "generations_dir": "/tmp/g",
            "symlink_path": "/tmp/s",
            "keep_generations": 5
        }"#;

        let manifest_path = dir.join("manifest.json");
        std::fs::write(&manifest_path, json).unwrap();

        let manifest = load(&manifest_path).unwrap();
        assert_eq!(manifest.secrets.len(), 1);
        assert_eq!(manifest.secrets[0].uid, Some(1000));
        assert_eq!(manifest.templates.len(), 1);
        assert_eq!(manifest.templates[0].uid, Some(0));
        assert_eq!(manifest.keep_generations, 5);

        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn test_secret_with_very_long_path() {
        let long_path = format!("/{}", "a/".repeat(100).trim_end_matches('/'));
        let json = format!(
            r#"{{
                "secrets": [{{"akeyless_path": "{long_path}", "file_path": "/tmp/long"}}],
                "templates": [],
                "generations_dir": "/tmp/g",
                "symlink_path": "/tmp/s"
            }}"#
        );
        let manifest: Manifest = serde_json::from_str(&json).unwrap();
        assert_eq!(manifest.secrets[0].akeyless_path, long_path);
    }

    #[test]
    fn test_load_nonexistent_file() {
        let result = load(std::path::Path::new("/tmp/nonexistent-manifest-akeyless-12345.json"));
        assert!(result.is_err(), "loading nonexistent file should fail");
        let err = result.unwrap_err().to_string();
        assert!(
            err.contains("reading manifest"),
            "error should mention reading: {err}"
        );
    }

    #[test]
    fn test_load_invalid_json() {
        let dir = std::env::temp_dir().join("akeyless-nix-test-manifest-invalid");
        let _ = std::fs::remove_dir_all(&dir);
        std::fs::create_dir_all(&dir).unwrap();

        let path = dir.join("bad.json");
        std::fs::write(&path, "not valid json").unwrap();

        let result = load(&path);
        assert!(result.is_err(), "invalid JSON should fail");
        let err = result.unwrap_err().to_string();
        assert!(
            err.contains("parsing manifest"),
            "error should mention parsing: {err}"
        );

        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn test_manifest_missing_required_fields() {
        let json = r#"{"secrets": []}"#;
        let result: Result<Manifest, _> = serde_json::from_str(json);
        assert!(
            result.is_err(),
            "missing generations_dir and symlink_path should fail"
        );
    }

    #[test]
    fn test_manifest_missing_secrets_field() {
        let json = r#"{
            "generations_dir": "/tmp/g",
            "symlink_path": "/tmp/s"
        }"#;
        let result: Result<Manifest, _> = serde_json::from_str(json);
        assert!(
            result.is_err(),
            "missing secrets field should fail"
        );
    }

    #[test]
    fn test_manifest_templates_default_empty() {
        let json = r#"{
            "secrets": [],
            "generations_dir": "/tmp/g",
            "symlink_path": "/tmp/s"
        }"#;
        let manifest: Manifest = serde_json::from_str(json).unwrap();
        assert!(
            manifest.templates.is_empty(),
            "templates should default to empty vec"
        );
    }

    #[test]
    fn test_parse_missing_required_field() {
        let json = r#"{
            "secrets": [{"file_path": "/tmp/test"}],
            "templates": [],
            "generations_dir": "/tmp/g",
            "symlink_path": "/tmp/s"
        }"#;
        let result: Result<Manifest, _> = serde_json::from_str(json);
        assert!(result.is_err(), "missing akeyless_path should fail");
    }

    #[test]
    fn test_parse_missing_generations_dir() {
        let json = r#"{
            "secrets": [],
            "templates": [],
            "symlink_path": "/tmp/s"
        }"#;
        let result: Result<Manifest, _> = serde_json::from_str(json);
        assert!(result.is_err(), "missing generations_dir should fail");
    }

    #[test]
    fn test_parse_missing_symlink_path() {
        let json = r#"{
            "secrets": [],
            "templates": [],
            "generations_dir": "/tmp/g"
        }"#;
        let result: Result<Manifest, _> = serde_json::from_str(json);
        assert!(result.is_err(), "missing symlink_path should fail");
    }

    #[test]
    fn test_secret_spec_default_owner_group() {
        let json = r#"{
            "secrets": [{"akeyless_path": "/test", "file_path": "/tmp/t"}],
            "templates": [],
            "generations_dir": "/tmp/g",
            "symlink_path": "/tmp/s"
        }"#;
        let manifest: Manifest = serde_json::from_str(json).unwrap();
        assert!(manifest.secrets[0].owner.is_empty());
        assert!(manifest.secrets[0].group.is_empty());
    }

    #[test]
    fn test_secret_spec_with_owner_group() {
        let json = r#"{
            "secrets": [{
                "akeyless_path": "/test",
                "file_path": "/tmp/t",
                "owner": "nginx",
                "group": "www-data"
            }],
            "templates": [],
            "generations_dir": "/tmp/g",
            "symlink_path": "/tmp/s"
        }"#;
        let manifest: Manifest = serde_json::from_str(json).unwrap();
        assert_eq!(manifest.secrets[0].owner, "nginx");
        assert_eq!(manifest.secrets[0].group, "www-data");
    }

    #[test]
    fn test_template_spec_uid_gid_and_owner_group() {
        let json = r#"{
            "secrets": [],
            "templates": [{
                "name": "config",
                "content": "test",
                "file_path": "/tmp/config",
                "owner": "app",
                "group": "app",
                "uid": 1001,
                "gid": 1001
            }],
            "generations_dir": "/tmp/g",
            "symlink_path": "/tmp/s"
        }"#;
        let manifest: Manifest = serde_json::from_str(json).unwrap();
        assert_eq!(manifest.templates[0].owner, "app");
        assert_eq!(manifest.templates[0].group, "app");
        assert_eq!(manifest.templates[0].uid, Some(1001));
        assert_eq!(manifest.templates[0].gid, Some(1001));
    }

    #[test]
    fn test_template_spec_defaults() {
        let json = r#"{
            "secrets": [],
            "templates": [{
                "name": "t",
                "content": "c",
                "file_path": "/tmp/t"
            }],
            "generations_dir": "/tmp/g",
            "symlink_path": "/tmp/s"
        }"#;
        let manifest: Manifest = serde_json::from_str(json).unwrap();
        assert_eq!(manifest.templates[0].mode, "0400");
        assert!(manifest.templates[0].owner.is_empty());
        assert!(manifest.templates[0].group.is_empty());
        assert_eq!(manifest.templates[0].uid, None);
        assert_eq!(manifest.templates[0].gid, None);
    }

    #[test]
    fn test_manifest_multiple_secrets_and_templates() {
        let json = r#"{
            "secrets": [
                {"akeyless_path": "/a", "file_path": "/tmp/a"},
                {"akeyless_path": "/b", "file_path": "/tmp/b"},
                {"akeyless_path": "/c", "file_path": "/tmp/c"}
            ],
            "templates": [
                {"name": "t1", "content": "c1", "file_path": "/tmp/t1"},
                {"name": "t2", "content": "c2", "file_path": "/tmp/t2"}
            ],
            "generations_dir": "/tmp/g",
            "symlink_path": "/tmp/s",
            "keep_generations": 10
        }"#;
        let manifest: Manifest = serde_json::from_str(json).unwrap();
        assert_eq!(manifest.secrets.len(), 3);
        assert_eq!(manifest.templates.len(), 2);
        assert_eq!(manifest.keep_generations, 10);
        assert_eq!(manifest.templates[0].name, "t1");
        assert_eq!(manifest.templates[1].name, "t2");
    }

    #[test]
    fn test_manifest_unknown_fields_ignored() {
        let json = r#"{
            "secrets": [],
            "templates": [],
            "generations_dir": "/tmp/g",
            "symlink_path": "/tmp/s",
            "unknown_field": "should be ignored",
            "extra": 42
        }"#;
        let result: Result<Manifest, _> = serde_json::from_str(json);
        if let Ok(m) = result {
            assert_eq!(m.generations_dir, "/tmp/g");
        }
    }

    #[test]
    fn test_manifest_keep_generations_zero() {
        let json = r#"{
            "secrets": [],
            "templates": [],
            "generations_dir": "/tmp/g",
            "symlink_path": "/tmp/s",
            "keep_generations": 0
        }"#;
        let manifest: Manifest = serde_json::from_str(json).unwrap();
        assert_eq!(manifest.keep_generations, 0);
    }

    #[test]
    fn test_secret_spec_for_test_defaults() {
        let spec = SecretSpec::for_test("/path", "/file");
        assert_eq!(spec.akeyless_path, "/path");
        assert_eq!(spec.file_path, "/file");
        assert_eq!(spec.mode, "0400");
        assert!(spec.owner.is_empty());
        assert!(spec.group.is_empty());
        assert_eq!(spec.uid, None);
        assert_eq!(spec.gid, None);
        assert!(spec.restart_units.is_empty());
        assert!(spec.reload_units.is_empty());
    }

    #[test]
    fn test_template_spec_for_test_defaults() {
        let spec = TemplateSpec::for_test("name", "content", "/file");
        assert_eq!(spec.name, "name");
        assert_eq!(spec.content, "content");
        assert_eq!(spec.file_path, "/file");
        assert_eq!(spec.mode, "0600");
        assert!(spec.owner.is_empty());
        assert!(spec.group.is_empty());
        assert_eq!(spec.uid, None);
        assert_eq!(spec.gid, None);
    }

    #[test]
    fn test_secret_with_special_chars_in_path() {
        let json = r#"{
            "secrets": [{"akeyless_path": "/pleme/prod/db-password.v2", "file_path": "/tmp/test"}],
            "templates": [],
            "generations_dir": "/tmp/g",
            "symlink_path": "/tmp/s"
        }"#;
        let manifest: Manifest = serde_json::from_str(json).unwrap();
        assert_eq!(manifest.secrets[0].akeyless_path, "/pleme/prod/db-password.v2");
    }

    #[test]
    fn test_template_with_all_fields() {
        let json = r#"{
            "secrets": [],
            "templates": [
                {
                    "name": "full",
                    "content": "data",
                    "file_path": "/tmp/full",
                    "mode": "0644",
                    "owner": "root",
                    "group": "wheel",
                    "uid": 0,
                    "gid": 0
                }
            ],
            "generations_dir": "/tmp/g",
            "symlink_path": "/tmp/s"
        }"#;
        let manifest: Manifest = serde_json::from_str(json).unwrap();
        assert_eq!(manifest.templates[0].mode, "0644");
        assert_eq!(manifest.templates[0].owner, "root");
        assert_eq!(manifest.templates[0].group, "wheel");
        assert_eq!(manifest.templates[0].uid, Some(0));
        assert_eq!(manifest.templates[0].gid, Some(0));
    }
}
